### ISSUE TITLE
🔨 [Chore] nestjs 개발 환경 설정

### ISSUE THREAD

**Issue by joosomi** [joosomi/mobinity#1]
## 🚀 Description
개발 시작을 위한 기본 nestjs 초기 환경 세팅

## ✅ TODO
- [x] NestJS 프로젝트 세팅 
- [x] 환경 변수 파일 (`.env`) 설정  -> `.env.sample` 필요 
- [x] 데이터베이스 연결, Docker 설정  (PostgreSQL 생각중)
- [x] ESLint 및 Prettier 설정
- [x] 로깅 및 에러 핸들링 - winston ,전역 exception filter 

## 📢 Notes
관계형 DB 선택 이유 - 사용자, 상품, 브랜드, 할인율 등등 테이블 간의 관계가 있기 때문에 관리하기에 더 적합한 것 같음.
