### ISSUE TITLE
✨ [Feature] 회원가입 및 로그인 API 

### ISSUE THREAD

**Issue by joosomi** [joosomi/mobinity#6]
## 🚀 Description
회원가입 및 로그인 서비스 로직 

## ✅ TODO

- [x] 회원가입 API - 가입시 사용자는 default BRONZE 유형으로 시작 
- [x] 로그인 API 
- [x] swagger 명세 작성 
- [x] authGuard 전역 설정 및 public decorator

## 📢 Notes
email, 유효성 검사 필요
아이디/ 비번이 다를 때 다른 예외처리 필요 

#### JWT 토큰 검증 과정
JWT 유효성 검사 (guard의 canActivate) → 페이로드 검증 및 사용자 정보 생성 (strategy의 validate) → 최종 인증 처리 (guar의 handleRequest - request에 사용자 정보 저장).
