### ISSUE TITLE
✨ [Feature] 브랜드별 상품 목록 조회 API 

### ISSUE THREAD

**Issue by joosomi** [joosomi/mobinity#8]
## 🚀 Description
브랜드별 상품 목록 조회 API 서비스 로직 설계 

- **브랜드별 상품 목록 조회**
    - 브랜드 이름(한글 또는 영어)으로 검색 시, 해당 브랜드에 속하는 상품 목록을 조회할 수 있는 기능을 구현합니다.
    - Pagination이 필요합니다.
    - 다음 사항이 응답에 포함되어야합니다.
        - 기본 금액
        - 할인된 금액
        - 전체 할인율
        - 상품 정보
        - 브랜드 정보

## ✅ TODO
- [x] 서비스 로직 설계 
- [x] swagger

## 🛠️ REFACTOR
- [ ] 쿼리로 검색시 대소문자 무시하고 검색하는 기능
- [ ] 유사한 회사 이름으로 조회 기능
